### ISSUE TITLE
‘const struct SensorData’ has no member named ‘angularAcc’ Error

### ISSUE THREAD

**Issue by shujaatak** [theilem/uavEE#3] opened 2018-11-30 18:21 UTC
These errors do not get away even after running catkin_make multiple times: 

uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h:66:74: **error: ‘const struct SensorData’ has no member named ‘angularAcc’**
 .acceleration.angular = Vector3ToXYZType<geometry_msgs::Vector3>(sd.angularAcc)

```
In file included from /home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/radio_comm/src/RadioComm.cpp:39:0:
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h: In function ‘simulation_interface::sensor_data apToRos(const SensorData&)’:
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h:66:74: error: ‘const struct SensorData’ has no member named ‘angularAcc’
 .acceleration.angular = Vector3ToXYZType<geometry_msgs::Vector3>(sd.angularAcc)
                                                                     ^
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h: In function ‘SensorData rosToAp(const sensor_data&)’:
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h:88:7: error: ‘struct SensorData’ has no member named ‘angularAcc’
  data.angularAcc = xyzTypeToVector3(sd.acceleration.angular);
       ^
In file included from /home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/src/AutopilotInterface/ApExtInterface.cpp:26:0:
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h: In function ‘simulation_interface::sensor_data apToRos(const SensorData&)’:
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h:66:74: error: ‘const struct SensorData’ has no member named ‘angularAcc’
  data.acceleration.angular = Vector3ToXYZType<geometry_msgs::Vector3>(sd.angularAcc);
                                                                          ^
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h: In function ‘SensorData rosToAp(const sensor_data&)’:
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h:88:7: error: ‘struct SensorData’ has no member named ‘angularAcc’
  data.angularAcc = xyzTypeToVector3(sd.acceleration.angular);
       ^
In file included from /home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/ground_station/src/Widgets/GraphicsMapView.cpp:27:0:
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h: In function ‘simulation_interface::sensor_data apToRos(const SensorData&)’:
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h:66:74: error: ‘const struct SensorData’ has no member named ‘angularAcc’
  data.acceleration.angular = Vector3ToXYZType<geometry_msgs::Vector3>(sd.angularAcc);
                                                                          ^
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h: In function ‘SensorData rosToAp(const sensor_data&)’:
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h:88:7: error: ‘struct SensorData’ has no member named ‘angularAcc’
  data.angularAcc = xyzTypeToVector3(sd.acceleration.angular);
       ^
autopilot_interface/CMakeFiles/autopilot_interface_node.dir/build.make:86: recipe for target 'autopilot_interface/CMakeFiles/autopilot_interface_node.dir/src/AutopilotInterface/ApExtInterface.cpp.o' failed
make[2]: *** [autopilot_interface/CMakeFiles/autopilot_interface_node.dir/src/AutopilotInterface/ApExtInterface.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 38%] Building CXX object ground_station/CMakeFiles/ground_station_node.dir/src/Widgets/WidgetSensorData.cpp.o
radio_comm/CMakeFiles/radio_comm_node.dir/build.make:86: recipe for target 'radio_comm/CMakeFiles/radio_comm_node.dir/src/RadioComm.cpp.o' failed
make[2]: *** [radio_comm/CMakeFiles/radio_comm_node.dir/src/RadioComm.cpp.o] Error 1
CMakeFiles/Makefile2:2176: recipe for target 'radio_comm/CMakeFiles/radio_comm_node.dir/all' failed
make[1]: *** [radio_comm/CMakeFiles/radio_comm_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 38%] Building CXX object ground_station/CMakeFiles/ground_station_node.dir/src/Widgets/WidgetSteadyStateAnalysis.cpp.o
In file included from /home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/AutopilotInterfaceHelper.h:32:0,
                 from /home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/src/autopilot_interface_node.cpp:26:
/usr/local/include/uavAP/Core/Framework/Helper.h: In instantiation of ‘void Helper::addFactory(PluginRestriction) [with FactoryType = AutopilotInterfaceFactory]’:
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/AutopilotInterfaceHelper.h:57:41:   required from here
/usr/local/include/uavAP/Core/Framework/Helper.h:142:40: error: ‘AutopilotInterfaceFactory::typeId’ cannot be used as a function
  std::string type = FactoryType::typeId();
                                        ^
ground_station/CMakeFiles/ground_station_node.dir/build.make:1344: recipe for target 'ground_station/CMakeFiles/ground_station_node.dir/src/Widgets/GraphicsMapView.cpp.o' failed
make[2]: *** [ground_station/CMakeFiles/ground_station_node.dir/src/Widgets/GraphicsMapView.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/ground_station/src/Widgets/WidgetSensorData.cpp:19:0:
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h: In function ‘simulation_interface::sensor_data apToRos(const SensorData&)’:
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h:66:74: error: ‘const struct SensorData’ has no member named ‘angularAcc’
  data.acceleration.angular = Vector3ToXYZType<geometry_msgs::Vector3>(sd.angularAcc);
                                                                          ^
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h: In function ‘SensorData rosToAp(const sensor_data&)’:
/home/shujaat/Desktop/Theilem-UAV/Theilem/uavEE/src/autopilot_interface/include/autopilot_interface/detail/uavAPConversions.h:88:7: error: ‘struct SensorData’ has no member named ‘angularAcc’
  data.angularAcc = xyzTypeToVector3(sd.acceleration.angular);
       ^
autopilot_interface/CMakeFiles/autopilot_interface_node.dir/build.make:62: recipe for target 'autopilot_interface/CMakeFiles/autopilot_interface_node.dir/src/autopilot_interface_node.cpp.o' failed
make[2]: *** [autopilot_interface/CMakeFiles/autopilot_interface_node.dir/src/autopilot_interface_node.cpp.o] Error 1
CMakeFiles/Makefile2:1642: recipe for target 'autopilot_interface/CMakeFiles/autopilot_interface_node.dir/all' failed
make[1]: *** [autopilot_interface/CMakeFiles/autopilot_interface_node.dir/all] Error 2
ground_station/CMakeFiles/ground_station_node.dir/build.make:1512: recipe for target 'ground_station/CMakeFiles/ground_station_node.dir/src/Widgets/WidgetSensorData.cpp.o' failed
make[2]: *** [ground_station/CMakeFiles/ground_station_node.dir/src/Widgets/WidgetSensorData.cpp.o] Error 1
CMakeFiles/Makefile2:3055: recipe for target 'ground_station/CMakeFiles/ground_station_node.dir/all' failed
make[1]: *** [ground_station/CMakeFiles/ground_station_node.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

```

**Comment by MacProSector** [comment] 2018-11-30 18:30
I apologize for all the problems. This issue is known and I have fixed it on the advanced_control branch but not yet on the master. However, I have just pushed the fix to the master. Please pull the latest master and try compiling. The problem is that the angular acceleration has been removed for a long time; however, the CMake Cache prevents the change from surfacing on our development machines during compilations, instead, only on brand-new compilations.

**Closed** 2018-11-30 18:40 UTC
